
services:

  backend:
    image: backend-app
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    image: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
