
services:

  backend:
    image: backend-app
    build: ./Backend
    ports:
      - "8080:8080"

  frontend:
    image: frontend-app
    build: ./frontend
    ports:
      - "80:80"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
